{{- /*
  Changes to this rendered manifest triggers a restart of the jupyterbook_pub
  pod as the pod specification includes an annotation with a checksum of this.
*/ -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "jupyterbook-pub-service.app.fullname" . }}-builder
  labels:
    {{- include "jupyterbook-pub-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.extraBuilderConfig }}
  {{- with .Values.extraBuilderConfig }}
  .{{- .name }}: |
  {{- if .value }}
    {{- .value | nindent 4 }}
  {{- else if .yaml }}
    {{- .yaml | toYaml | nindent 4 }}
  {{- else if .json }}
    {{- .json | mustToJson | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- end }}
