{{- /*
  Changes to this rendered manifest triggers a restart of the jupyterbook_pub
  pod as the pod specification includes an annotation with a checksum of this.
*/ -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "jupyterbook-pub-service.app.fullname" . }}
  labels:
    {{- include "jupyterbook-pub-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- /*
    To restart the jupyterbook_pub pod only when relevant, we pick out the
    chart configuration actually consumed in the mounted jupyterbook_pub_config.py
    file.
  */}}
  builtin-chart-config.py: |
    # App config
    c.JupyterBookPubApp.executor_class = "jupyterbook_pub.executor.KubernetesExecutor"
    c.JupyterBookPubApp.storage_root = "/srv"
    # KubernetesExecutor config
    import json

    c.KubernetesExecutor.builder_config_secret = {{ print (include "jupyterbook-pub-service.app.fullname" .) "-builder" | quote }}
    {{- if .Values.extraBuildConfig }}
    c.KubernetesExecutor.builder_config_name = {{ .Values.extraBuildConfig.name | quote }}
    {{- end }}

    # Storage used by the main app
    c.KubernetesExecutor.storage_volume = json.loads(
      {{ include "jupyterbook-pub-service.storageVolume" . | fromYaml | mustToJson | quote }}
    )
    # Release namespace
    c.KubernetesExecutor.namespace = {{ .Release.Namespace | quote }}
    c.KubernetesExecutor.image = {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion | quote }}
  chart-config.yaml: |
    {{- pick .Values "custom" "config" "extraConfig" | toYaml | nindent 4 }}

  {{- /* Glob files to allow them to be mounted by the jupyterbook_pub pod */}}
  {{- /* key=filename: value=content */}}
  {{- (.Files.Glob "mounted-files/*").AsConfig | nindent 2 }}
